CREATE TABLE logs(
    log_id SERIAL PRIMARY KEY,
    id VARCHAR(255) NOT NULL,
    in_network BOOLEAN NOT NULL,
    international BOOLEAN NOT NULL,
    from_num VARCHAR(255) NOT NULL,
    to_num VARCHAR(255) NOT NULL,
    direction VARCHAR(255) NOT NULL,
    length_time INTEGER NOT NULL,
    start_time VARCHAR(255) NOT NULL,
    end_time VARCHAR(255) NOT NULL,
    charge INTEGER NOT NULL,
    rate INTEGER NOT NULL,
    destination_device_name VARCHAR(255) NULL,
    source_device_name VARCHAR(255) NULL,
    destination_user_full_name VARCHAR(255) NULL,
    destination_user VARCHAR(255) NULL,
    destination_sip_id VARCHAR(255) NULL,
    destination_extension VARCHAR(255) NULL,
    source_user_full_name VARCHAR(255) NOT NULL,
    source_user VARCHAR(255) NOT NULL,
    custom_tag VARCHAR(255) NULL,
    source_sip_id VARCHAR(255) NOT NULL,
    source_extension VARCHAR(255) NOT NULL,
    result VARCHAR(255) NOT NULL,
    recorded BOOLEAN NOT NULL
);